const userSchema = {
    "type": "object",
    "properties": {
      "login": { "type": "string" },
      "id": { "type": "integer" },
      "node_id": { "type": "string" },
      "avatar_url": { "type": "string", "format": "uri" },
      "gravatar_id": { "type": "string" },
      "url": { "type": "string", "format": "uri" },
      "html_url": { "type": "string", "format": "uri" },
      "followers_url": { "type": "string" },
      "following_url": { "type": "string" },
      "gists_url": { "type": "string", "format": "uri-template" },
      "starred_url": { "type": "string", "format": "uri-template" },
      "subscriptions_url": { "type": "string", "format": "uri" },
      "organizations_url": { "type": "string", "format": "uri" },
      "repos_url": { "type": "string", "format": "uri" },
      "events_url": { "type": "string", "format": "uri-template" },
      "received_events_url": { "type": "string", "format": "uri" },
      "type": { "type": "string" },
      "user_view_type": { "type": "string" },
      "site_admin": { "type": "boolean" },
      "name": { "type": ["string", "null"] },
      "company": { "type": ["string", "null"] },
      "blog": { "type": "string" },
      "location": { "type": ["string", "null"] },
      "email": { "type": ["string", "null"], "format": "email" },
      "hireable": { "type": ["boolean", "null"] },
      "bio": { "type": ["string", "null"] },
      "twitter_username": { "type": ["string", "null"] },
      "public_repos": { "type": "integer" },
      "public_gists": { "type": "integer" },
      "followers": { "type": "integer" },
      "following": { "type": "integer" },
      "created_at": { "type": "string", "format": "date-time" },
      "updated_at": { "type": "string", "format": "date-time" }
    },
    "required": [
      "login",
      "id",
      "node_id",
      "avatar_url",
      "url",
      "html_url",
      "followers_url",
      "following_url",
      "gists_url",
      "starred_url",
      "subscriptions_url",
      "organizations_url",
      "repos_url",
      "events_url",
      "received_events_url",
      "type",
      "user_view_type",
      "site_admin",
      "public_repos",
      "public_gists",
      "followers",
      "following",
      "created_at",
      "updated_at"
    ],
    "additionalProperties": false
  }

  module.exports=userSchema;